<?php

namespace tests\HtmlElements;


use QATools\PHPUnitExtension\AbstractQAToolsTestCase;
use tests\HtmlElements\pages\HomePage;

class DemoTest extends AbstractQAToolsTestCase
{

	public function testExample()
	{
		$homePage = new HomePage($this->pageFactory);
		$homePage->open();

		$homePage->changeCurrency('EUR');

		$homePage->changeLanguage('Russian');

		foreach ( $homePage->getRadioGroup() as $radioButton ) {
			if ( $radioButton->isSelected() ) {
				echo 'yes';
			}
		}

		$homePage->selectRadioButton(4);

		$homePage->loginInline('user-a', 'password-a');

		$errorMessage1 = $homePage->loginViaSidebox('user-a', 'password-a');

		$errorMessage2 = $homePage->loginViaSidebar('user-a', 'password-a');

		$name1 = $homePage->getAutoGeneratedElementName();

		$name2 = $homePage->getOverrideElementName();
	}

}
